repos:
# Python linting
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
      files: |
        ^somos/.*\.py$
        ^tests/.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      files: |
        ^somos/.*\.py$
        ^tests/.*\.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      files: |
        ^somos/.*\.py$
        ^tests/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    - id: mypy
      files: |
        ^somos/.*\.py$
        ^tests/.*\.py$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-r", "."]

  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -B -m unittest discover -s tests
        language: system
        pass_filenames: false