name: Build
run-name: Build by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - somos/**

  workflow_dispatch:
    inputs:
      version:
        description: 'Version type to bump (major, minor, patch)'
        required: false
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git config
        run: |
          git config --global user.name "thatgaypigeon"
          git config --global user.email "pigeon43.stuff@gmail.com"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install coverage Bandit pre-commit bump-my-version
        # run: pip install -r requirements.txt

      # Bump version
      - name: Bump version
        id: bump
        run: bump-my-version bump ${{ github.event.inputs.version || 'patch' }}

      # Lint
      - name: Lint
        run: pre-commit run --all-files

      # Code coverage
      - name: Run tests with coverage
        run: coverage run -m unittest discover tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      # Security checks
      - name: Security checks
        run: bandit -r .

      # Pre-deploy commit
      - name: Pre-deploy commit
        run: |
          git add .
          git commit -m "Pre-deploy commit for ${{ steps.bump.outputs.new_version }}"

      # Stash version
      - name: Save version
        run: echo "${{ steps.bump.outputs.new_version }}" > version.txt

      - name: Upload version
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt

  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Git config
        run: |
          git config --global user.name "thatgaypigeon"
          git config --global user.email "pigeon43.stuff@gmail.com"

      - name: Checkout
        uses: actions/checkout@v4

      # Fetch version number
      - name: Download version
        uses: actions/download-artifact@v2
        with:
          name: version

      - name: Set version
        id: version
        run: echo "::set-output name=version::$(cat version.txt)"

      # Deploy build
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      # Deploy to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
