name: Build & Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # - name: Configure git credentials
      #   run: |
      #     git config user.name github-actions[bot]
      #     git config user.email github-actions[bot]@users.noreply.github.com

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Install dependencies
        run: pip install -r docs/src/requirements.txt
      
      - name: Build documentation
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
